In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance.csv")

In [3]:
dataset.head(5)

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
dataset.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
age         1338 non-null int64
sex         1338 non-null object
bmi         1338 non-null float64
children    1338 non-null int64
smoker      1338 non-null object
region      1338 non-null object
charges     1338 non-null float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.2+ KB


In [6]:
x=dataset.iloc[:,0:6].values
y=dataset.iloc[:,6].values

In [7]:
x

array([[19, 'female', 27.9, 0, 'yes', 'southwest'],
       [18, 'male', 33.77, 1, 'no', 'southeast'],
       [28, 'male', 33.0, 3, 'no', 'southeast'],
       ...,
       [18, 'female', 36.85, 0, 'no', 'southeast'],
       [21, 'female', 25.8, 0, 'no', 'southwest'],
       [61, 'female', 29.07, 0, 'yes', 'northwest']], dtype=object)

In [8]:
y

array([16884.924 ,  1725.5523,  4449.462 , ...,  1629.8335,  2007.945 ,
       29141.3603])

In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[1,4,5])],remainder="passthrough")
#coverts data into binary form
x=ct.fit_transform(x)

In [10]:
x.shape

(1338, 11)

In [11]:
y.shape

(1338,)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0) #test_size=0.2 is 20% testing data

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [20]:
from tensorflow.keras.models import Sequential #used to initialize
from tensorflow.keras.layers import Dense #used to add layers

In [15]:
reg=Sequential()

In [21]:
reg.add(Dense(6,kernel_initializer ="random_uniform",activation="relu"))

In [22]:
reg.add(Dense(12,kernel_initializer ="random_uniform",activation="relu"))

In [23]:
reg.add(Dense(1,kernel_initializer ="random_uniform",activation="relu"))

In [24]:
reg.compile("adam","mean_squared_error",metrics=["mse"]) #nick name for batch gradient is adam.

In [25]:
reg.fit(x_train,y_train,batch_size=32,epochs=1000)

Epoch 1/1000
1070/1070 [==============================] - 2s 2ms/sample - loss: 317637358.0561 - mean_squared_error: 317637376.0000
Epoch 2/1000
1070/1070 [==============================] - 0s 161us/sample - loss: 317637360.5682 - mean_squared_error: 317637376.0000
Epoch 3/1000
1070/1070 [==============================] - 0s 133us/sample - loss: 317637356.1421 - mean_squared_error: 317637312.0000
Epoch 4/1000
1070/1070 [==============================] - 0s 125us/sample - loss: 317637362.6617 - mean_squared_error: 317637344.0000
Epoch 5/1000
1070/1070 [==============================] - 0s 134us/sample - loss: 317637361.5252 - mean_squared_error: 317637344.0000
Epoch 6/1000
1070/1070 [==============================] - 0s 148us/sample - loss: 317637355.4841 - mean_squared_error: 317637344.0000
Epoch 7/1000
1070/1070 [==============================] - 0s 125us/sample - loss: 317637354.0785 - mean_squared_error: 317637344.0000
Epoch 8/1000
1070/1070 [==============================] - 0s 133

1070/1070 [==============================] - 0s 82us/sample - loss: 317637360.9421 - mean_squared_error: 317637408.0000
Epoch 63/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637354.6766 - mean_squared_error: 317637376.0000
Epoch 64/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637361.7645 - mean_squared_error: 317637376.0000
Epoch 65/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637359.7607 - mean_squared_error: 317637344.0000
Epoch 66/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637358.5645 - mean_squared_error: 317637376.0000
Epoch 67/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637361.4056 - mean_squared_error: 317637344.0000
Epoch 68/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637355.7832 - mean_squared_error: 317637312.0000
Epoch 69/1000
1070/1070 [==============================] - 0s 75us/sample - 

1070/1070 [==============================] - 0s 82us/sample - loss: 317637357.8467 - mean_squared_error: 317637408.0000
Epoch 124/1000
1070/1070 [==============================] - 0s 74us/sample - loss: 317637356.9794 - mean_squared_error: 317637280.0000
Epoch 125/1000
1070/1070 [==============================] - 0s 78us/sample - loss: 317637361.1065 - mean_squared_error: 317637376.0000
Epoch 126/1000
1070/1070 [==============================] - 0s 78us/sample - loss: 317637357.6822 - mean_squared_error: 317637344.0000
Epoch 127/1000
1070/1070 [==============================] - 0s 78us/sample - loss: 317637359.0729 - mean_squared_error: 317637344.0000
Epoch 128/1000
1070/1070 [==============================] - 0s 78us/sample - loss: 317637362.8112 - mean_squared_error: 317637408.0000
Epoch 129/1000
1070/1070 [==============================] - 0s 74us/sample - loss: 317637361.0467 - mean_squared_error: 317637344.0000
Epoch 130/1000
1070/1070 [==============================] - 0s 75us/sa

1070/1070 [==============================] - 0s 78us/sample - loss: 317637362.5421 - mean_squared_error: 317637376.0000
Epoch 184/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637355.0056 - mean_squared_error: 317637344.0000
Epoch 185/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637361.4654 - mean_squared_error: 317637376.0000
Epoch 186/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637357.8168 - mean_squared_error: 317637344.0000
Epoch 187/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637357.9364 - mean_squared_error: 317637376.0000
Epoch 188/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637362.6019 - mean_squared_error: 317637408.0000
Epoch 189/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637358.7140 - mean_squared_error: 317637408.0000
Epoch 190/1000
1070/1070 [==============================] - 0s 75us/sa

1070/1070 [==============================] - 0s 78us/sample - loss: 317637360.6879 - mean_squared_error: 317637344.0000
Epoch 244/1000
1070/1070 [==============================] - 0s 78us/sample - loss: 317637355.4243 - mean_squared_error: 317637344.0000
Epoch 245/1000
1070/1070 [==============================] - 0s 78us/sample - loss: 317637356.8897 - mean_squared_error: 317637376.0000
Epoch 246/1000
1070/1070 [==============================] - 0s 70us/sample - loss: 317637354.1533 - mean_squared_error: 317637376.0000
Epoch 247/1000
1070/1070 [==============================] - 0s 78us/sample - loss: 317637354.1682 - mean_squared_error: 317637312.0000
Epoch 248/1000
1070/1070 [==============================] - 0s 81us/sample - loss: 317637359.3720 - mean_squared_error: 317637344.0000
Epoch 249/1000
1070/1070 [==============================] - 0s 83us/sample - loss: 317637359.0729 - mean_squared_error: 317637376.0000
Epoch 250/1000
1070/1070 [==============================] - 0s 78us/sa

1070/1070 [==============================] - 0s 75us/sample - loss: 317637361.9140 - mean_squared_error: 317637344.0000
Epoch 304/1000
1070/1070 [==============================] - 0s 78us/sample - loss: 317637356.1421 - mean_squared_error: 317637344.0000
Epoch 305/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637357.6374 - mean_squared_error: 317637344.0000
Epoch 306/1000
1070/1070 [==============================] - 0s 78us/sample - loss: 317637360.4187 - mean_squared_error: 317637344.0000
Epoch 307/1000
1070/1070 [==============================] - 0s 78us/sample - loss: 317637362.6019 - mean_squared_error: 317637376.0000
Epoch 308/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637361.4654 - mean_squared_error: 317637376.0000
Epoch 309/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637358.3551 - mean_squared_error: 317637376.0000
Epoch 310/1000
1070/1070 [==============================] - 0s 69us/sa

1070/1070 [==============================] - 0s 90us/sample - loss: 317637360.8075 - mean_squared_error: 317637376.0000
Epoch 364/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637361.1963 - mean_squared_error: 317637376.0000
Epoch 365/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637359.6710 - mean_squared_error: 317637408.0000
Epoch 366/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637362.4822 - mean_squared_error: 317637344.0000
Epoch 367/1000
1070/1070 [==============================] - 0s 90us/sample - loss: 317637357.0991 - mean_squared_error: 317637344.0000
Epoch 368/1000
1070/1070 [==============================] - 0s 97us/sample - loss: 317637358.1159 - mean_squared_error: 317637344.0000
Epoch 369/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637359.3720 - mean_squared_error: 317637344.0000
Epoch 370/1000
1070/1070 [==============================] - 0s 67us/sa

1070/1070 [==============================] - 0s 82us/sample - loss: 317637359.1028 - mean_squared_error: 317637440.0000
Epoch 424/1000
1070/1070 [==============================] - 0s 70us/sample - loss: 317637358.2355 - mean_squared_error: 317637408.0000
Epoch 425/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637362.7813 - mean_squared_error: 317637344.0000
Epoch 426/1000
1070/1070 [==============================] - 0s 67us/sample - loss: 317637361.4654 - mean_squared_error: 317637344.0000
Epoch 427/1000
1070/1070 [==============================] - 0s 77us/sample - loss: 317637355.3047 - mean_squared_error: 317637376.0000
Epoch 428/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637359.1327 - mean_squared_error: 317637344.0000
Epoch 429/1000
1070/1070 [==============================] - 0s 105us/sample - loss: 317637360.6879 - mean_squared_error: 317637376.0000
Epoch 430/1000
1070/1070 [==============================] - 0s 97us/s

1070/1070 [==============================] - 0s 105us/sample - loss: 317637356.6804 - mean_squared_error: 317637376.0000
Epoch 484/1000
1070/1070 [==============================] - 0s 90us/sample - loss: 317637355.4841 - mean_squared_error: 317637376.0000
Epoch 485/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637356.2318 - mean_squared_error: 317637344.0000
Epoch 486/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637358.9533 - mean_squared_error: 317637344.0000
Epoch 487/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637358.8336 - mean_squared_error: 317637344.0000
Epoch 488/1000
1070/1070 [==============================] - 0s 81us/sample - loss: 317637363.2598 - mean_squared_error: 317637408.0000
Epoch 489/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637361.2860 - mean_squared_error: 317637376.0000
Epoch 490/1000
1070/1070 [==============================] - 0s 82us/s

1070/1070 [==============================] - 0s 90us/sample - loss: 317637357.9364 - mean_squared_error: 317637344.0000
Epoch 544/1000
1070/1070 [==============================] - 0s 90us/sample - loss: 317637356.2467 - mean_squared_error: 317637344.0000
Epoch 545/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637354.7963 - mean_squared_error: 317637376.0000
Epoch 546/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637360.1196 - mean_squared_error: 317637312.0000
Epoch 547/1000
1070/1070 [==============================] - 0s 84us/sample - loss: 317637356.0523 - mean_squared_error: 317637312.0000
Epoch 548/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637356.9196 - mean_squared_error: 317637408.0000
Epoch 549/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637357.0692 - mean_squared_error: 317637344.0000
Epoch 550/1000
1070/1070 [==============================] - 0s 90us/sa

1070/1070 [==============================] - 0s 82us/sample - loss: 317637358.4748 - mean_squared_error: 317637376.0000
Epoch 604/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637360.5682 - mean_squared_error: 317637344.0000
Epoch 605/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637357.8766 - mean_squared_error: 317637344.0000
Epoch 606/1000
1070/1070 [==============================] - 0s 90us/sample - loss: 317637359.9103 - mean_squared_error: 317637344.0000
Epoch 607/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637357.8766 - mean_squared_error: 317637408.0000
Epoch 608/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637357.6075 - mean_squared_error: 317637344.0000
Epoch 609/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637357.8168 - mean_squared_error: 317637408.0000
Epoch 610/1000
1070/1070 [==============================] - 0s 86us/sa

1070/1070 [==============================] - 0s 90us/sample - loss: 317637358.2953 - mean_squared_error: 317637344.0000
Epoch 664/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637360.6280 - mean_squared_error: 317637344.0000
Epoch 665/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637355.9028 - mean_squared_error: 317637312.0000
Epoch 666/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637356.0224 - mean_squared_error: 317637344.0000
Epoch 667/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637356.6804 - mean_squared_error: 317637344.0000
Epoch 668/1000
1070/1070 [==============================] - 0s 74us/sample - loss: 317637352.7925 - mean_squared_error: 317637376.0000
Epoch 669/1000
1070/1070 [==============================] - 0s 78us/sample - loss: 317637359.7308 - mean_squared_error: 317637344.0000
Epoch 670/1000
1070/1070 [==============================] - 0s 81us/sa

1070/1070 [==============================] - 0s 82us/sample - loss: 317637358.2056 - mean_squared_error: 317637408.0000
Epoch 724/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637354.4075 - mean_squared_error: 317637312.0000
Epoch 725/1000
1070/1070 [==============================] - 0s 83us/sample - loss: 317637362.1533 - mean_squared_error: 317637376.0000
Epoch 726/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637356.0822 - mean_squared_error: 317637312.0000
Epoch 727/1000
1070/1070 [==============================] - 0s 81us/sample - loss: 317637362.1533 - mean_squared_error: 317637312.0000
Epoch 728/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637361.2860 - mean_squared_error: 317637376.0000
Epoch 729/1000
1070/1070 [==============================] - 0s 80us/sample - loss: 317637357.8168 - mean_squared_error: 317637344.0000
Epoch 730/1000
1070/1070 [==============================] - 0s 82us/sa

1070/1070 [==============================] - 0s 90us/sample - loss: 317637361.7346 - mean_squared_error: 317637344.0000
Epoch 783/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637362.0037 - mean_squared_error: 317637344.0000
Epoch 784/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637353.6897 - mean_squared_error: 317637344.0000
Epoch 785/1000
1070/1070 [==============================] - 0s 97us/sample - loss: 317637359.6112 - mean_squared_error: 317637344.0000
Epoch 786/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637356.6206 - mean_squared_error: 317637344.0000
Epoch 787/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637361.0766 - mean_squared_error: 317637344.0000
Epoch 788/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637360.2093 - mean_squared_error: 317637344.0000
Epoch 789/1000
1070/1070 [==============================] - 0s 90us/sa

1070/1070 [==============================] - 0s 90us/sample - loss: 317637354.5869 - mean_squared_error: 317637376.0000
Epoch 843/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637357.6075 - mean_squared_error: 317637312.0000
Epoch 844/1000
1070/1070 [==============================] - 0s 105us/sample - loss: 317637362.2430 - mean_squared_error: 317637408.0000
Epoch 845/1000
1070/1070 [==============================] - 0s 90us/sample - loss: 317637356.3813 - mean_squared_error: 317637344.0000
Epoch 846/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637358.1159 - mean_squared_error: 317637376.0000
Epoch 847/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637357.5776 - mean_squared_error: 317637344.0000
Epoch 848/1000
1070/1070 [==============================] - 0s 75us/sample - loss: 317637356.5009 - mean_squared_error: 317637376.0000
Epoch 849/1000
1070/1070 [==============================] - 0s 71us/s

1070/1070 [==============================] - 0s 92us/sample - loss: 317637357.9664 - mean_squared_error: 317637376.0000
Epoch 903/1000
1070/1070 [==============================] - 0s 97us/sample - loss: 317637357.6374 - mean_squared_error: 317637344.0000
Epoch 904/1000
1070/1070 [==============================] - 0s 82us/sample - loss: 317637355.9626 - mean_squared_error: 317637344.0000
Epoch 905/1000
1070/1070 [==============================] - 0s 90us/sample - loss: 317637362.8112 - mean_squared_error: 317637344.0000
Epoch 906/1000
1070/1070 [==============================] - 0s 127us/sample - loss: 317637359.0729 - mean_squared_error: 317637376.0000
Epoch 907/1000
1070/1070 [==============================] - 0s 90us/sample - loss: 317637360.2692 - mean_squared_error: 317637376.0000
Epoch 908/1000
1070/1070 [==============================] - 0s 72us/sample - loss: 317637356.0822 - mean_squared_error: 317637344.0000
Epoch 909/1000
1070/1070 [==============================] - 0s 82us/s

1070/1070 [==============================] - 0s 179us/sample - loss: 317637358.0112 - mean_squared_error: 317637344.0000
Epoch 963/1000
1070/1070 [==============================] - 0s 142us/sample - loss: 317637358.2056 - mean_squared_error: 317637312.0000
Epoch 964/1000
1070/1070 [==============================] - 0s 85us/sample - loss: 317637356.3813 - mean_squared_error: 317637376.0000
Epoch 965/1000
1070/1070 [==============================] - 0s 121us/sample - loss: 317637356.4411 - mean_squared_error: 317637312.0000
Epoch 966/1000
1070/1070 [==============================] - 0s 120us/sample - loss: 317637358.2654 - mean_squared_error: 317637408.0000
Epoch 967/1000
1070/1070 [==============================] - 0s 127us/sample - loss: 317637359.8505 - mean_squared_error: 317637376.0000
Epoch 968/1000
1070/1070 [==============================] - 0s 157us/sample - loss: 317637357.1589 - mean_squared_error: 317637344.0000
Epoch 969/1000
1070/1070 [==============================] - 0s 1

In [26]:
ypred=reg.predict(x_test)

In [27]:
ypred

array([[ 0.],
       [-0.],
       [ 0.],
       [-0.],
       [-0.],
       [-0.],
       [ 0.],
       [-0.],
       [-0.],
       [ 0.],
       [ 0.],
       [-0.],
       [-0.],
       [-0.],
       [ 0.],
       [ 0.],
       [-0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [-0.],
       [-0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [-0.],
       [ 0.],
       [-0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [-0.],
       [ 0.],
       [-0.],
       [-0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [-0.],
       [ 0.],
       [-0.],
       [ 0.],
       [-0.],
       [ 0.],
       [-0.],
       [ 0.],
       [ 0.],
       [-0.],
       [ 0.],
       [ 0.],
       [-0.],
       [ 0.],
       [-0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [-0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [-0.],
      

In [28]:
y_test

array([ 9724.53    ,  8547.6913  , 45702.02235 , 12950.0712  ,
        9644.2525  ,  4500.33925 ,  2198.18985 , 11436.73815 ,
        7537.1639  ,  5425.02335 ,  6753.038   , 10493.9458  ,
        7337.748   ,  4185.0979  , 18310.742   , 10702.6424  ,
       12523.6048  ,  3490.5491  ,  6457.8434  , 33475.81715 ,
       23967.38305 , 12643.3778  , 23045.56616 , 23065.4207  ,
        1674.6323  ,  4667.60765 ,  3732.6251  ,  7682.67    ,
        3756.6216  ,  8413.46305 ,  8059.6791  , 48970.2476  ,
       12979.358   , 20630.28351 , 14571.8908  ,  4137.5227  ,
        8347.1643  , 51194.55914 , 40003.33225 ,  1880.487   ,
        5458.04645 ,  2867.1196  , 20149.3229  , 47496.49445 ,
       36149.4835  , 26018.95052 , 19749.38338 ,  6940.90985 ,
        4718.20355 , 22192.43711 ,  2899.48935 , 18838.70366 ,
       23568.272   , 46255.1125  , 24227.33724 ,  3268.84665 ,
        2322.6218  ,  8827.2099  , 14478.33015 , 13112.6048  ,
        1253.936   , 46718.16325 , 13919.8229  ,  9630.

In [29]:
dataset.head(10)

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960
7   37  female  27.740         3     no  northwest   7281.50560
8   37    male  29.830         2     no  northeast   6406.41070
9   60  female  25.840         0     no  northwest  28923.13692

In [30]:
yp=reg.predict(sc.transform(ct.transform([[19,"female",27.900,0,"yes","southwest"]])))

In [31]:
yp

array([[0.]], dtype=float32)

In [32]:
yp=reg.predict(sc.transform(ct.transform([[18,"male",33.770,1,"no","southeast"]])))

In [33]:
yp

array([[0.]], dtype=float32)